; ---------------------------------------------------------------------------
; - Stars - Equates (equates.inc)                                           -
; - Copyright (C) 1998-2024 Alexandru Groza of Microprogramming TECHNIQUES  -
; - All rights reserved.                                                    -
; ---------------------------------------------------------------------------
; - License: GNU General Public License v3.0                                -
; ---------------------------------------------------------------------------

; general program equates
; ---------------------------------------------------------------------------
  kStarMinimumCount      EQU  0
  kStarMaximumCount      EQU  49
  kInflatedMinimumCount  EQU  0
  kInflatedMaximumCount  EQU  9
  kStarSequenceSpeed     EQU  250
  kStarExplodeFrames     EQU  5
  kStarExplodeFrameSpeed EQU  250

  kStarExtinct           EQU  0
  kStarNew               EQU  2
  kStarShine             EQU  4
  kStarInflate           EQU  6
  kStarExploded          EQU  12
